### PR TITLE
Add a CI workflow that does build+test

### PR DESCRIPTION
**Pull request by cgwalters**
This is a baseline I'd expect to see on a project hosted on Github.

### CODE REVIEW

**Comment by cgwalters** [comment]
Example run of this here https://github.com/cgwalters/camgi.rs/actions/runs/4409593577/jobs/7726074266

**Comment by elmiko** [comment]
this is similar to the format and unit test workflow, i wonder if we should combine them, or perhaps remove the old one and include a format check in this one?

**Comment by cgwalters** [comment]
Sorry, I'd missed that that runs `cargo test` too.

**Comment by cgwalters** [comment]
Replaced it with this one which is better for multiple reasons (you *will* notice the caching e.g.)

**Comment by elmiko** [comment]
> Replaced it with this one which is better for multiple reasons (you _will_ notice the caching e.g.)

++, i appreciate it =)

**Comment by cgwalters** [comment]
Followup in https://github.com/elmiko/camgi.rs/pull/39

**Pull request merged**
